version: '3'
services:
    mysql-5.7:
        image: dockerpull.pw/mysql:5.7.44
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
        ports:
            - 3306:3306
        tmpfs:
            - /var/lib/mysql
